import Link from "next/link";
import { redirect } from "next/navigation";
import {
  BadgeCheck,
  CircleDashed,
  Clock3,
  FileText,
  IndianRupee,
  Plus,
  ReceiptText,
} from "lucide-react";

import { PortalShell } from "@/components/shared/portal-shell";
import { AgentSidebar } from "@/components/agent/agent-sidebar";
import { InfoPanel } from "@/components/shared/info-panel";
import { StatCard } from "@/components/shared/stat-card";
import { createClient } from "@/lib/supabase/server";

type QuoteBuilderPayload = {
  departureCity?: string;
  travelDates?: string;
  nights?: string;
  adults?: number;
  children?: number;
};

type QuoteRow = {
  id: string;
  quote_ref: string | null;
  destination: string | null;
  amount: number | null;
  status: string | null;
  customer_name: string | null;
  customer_email: string | null;
  customer_phone: string | null;
  builder_payload: QuoteBuilderPayload | null;
  created_at: string | null;
  updated_at: string | null;
};

type AgentQuotesPageProps = {
  searchParams?: Promise<{
    created?: string;
  }>;
};

function formatCurrency(value: number | null | undefined) {
  const num = Number(value ?? 0);
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(Number.isFinite(num) ? num : 0);
}

function formatDate(value: string | null | undefined) {
  if (!value) return "—";

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";

  return new Intl.DateTimeFormat("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(date);
}

function formatDateTime(value: string | null | undefined) {
  if (!value) return "—";

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";

  return new Intl.DateTimeFormat("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

function normalizeStatus(status: string | null | undefined) {
  const value = (status || "draft").trim().toLowerCase();

  if (value === "approved") return "Approved";
  if (value === "sent") return "Sent";
  if (value === "paid") return "Paid";
  if (value === "cancelled") return "Cancelled";
  if (value === "expired") return "Expired";
  if (value === "rejected") return "Rejected";
  if (value === "pending") return "Pending";

  return "Draft";
}

function getStatusClasses(status: string | null | undefined) {
  const value = (status || "draft").trim().toLowerCase();

  if (value === "approved") {
    return "border-emerald-200 bg-emerald-50 text-emerald-700";
  }

  if (value === "sent") {
    return "border-sky-200 bg-sky-50 text-sky-700";
  }

  if (value === "paid") {
    return "border-violet-200 bg-violet-50 text-violet-700";
  }

  if (value === "cancelled" || value === "rejected" || value === "expired") {
    return "border-rose-200 bg-rose-50 text-rose-700";
  }

  if (value === "pending") {
    return "border-amber-200 bg-amber-50 text-amber-700";
  }

  return "border-slate-200 bg-slate-50 text-slate-700";
}

function safeNumber(value: number | null | undefined) {
  const num = Number(value ?? 0);
  return Number.isFinite(num) ? num : 0;
}

export default async function AgentQuotesPage({ searchParams }: AgentQuotesPageProps) {
  const resolvedSearchParams = searchParams ? await searchParams : {};
  const createdQuoteRef = resolvedSearchParams?.created || "";

  const supabase = await createClient();

  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    redirect("/agent/login");
  }

  if (user.app_metadata?.role !== "agent") {
    redirect("/agent/login");
  }

  const { data: agent, error: agentError } = await supabase
    .from("agents")
    .select("id")
    .eq("auth_user_id", user.id)
    .single();

  if (agentError || !agent?.id) {
    redirect("/agent/login");
  }

  const { data: quotesData, error: quotesError } = await supabase
    .from("quotes")
    .select(`
      id,
      quote_ref,
      destination,
      amount,
      status,
      customer_name,
      customer_email,
      customer_phone,
      builder_payload,
      created_at,
      updated_at
    `)
    .eq("agent_id", agent.id)
    .order("created_at", { ascending: false });

  const quotes = ((quotesData as QuoteRow[] | null) || []) as QuoteRow[];

  const totalQuotes = quotes.length;
  const draftQuotes = quotes.filter((quote) => {
    const value = (quote.status || "").toLowerCase();
    return value === "draft" || value === "pending";
  }).length;
  const approvedQuotes = quotes.filter((quote) => (quote.status || "").toLowerCase() === "approved").length;
  const totalQuoteValue = quotes.reduce((sum, quote) => sum + safeNumber(quote.amount), 0);

  return (
    <PortalShell
      title="Quotes"
      subtitle="Create, review, and track all quotes generated by your agent account."
      sidebar={<AgentSidebar />}
    >
      <div className="space-y-6">
        {createdQuoteRef ? (
          <div className="rounded-[28px] border border-emerald-200 bg-emerald-50 px-5 py-4">
            <div className="flex items-start gap-3">
              <BadgeCheck className="mt-0.5 h-5 w-5 text-emerald-600" />
              <div>
                <p className="text-sm font-semibold text-emerald-800">Quote created successfully</p>
                <p className="mt-1 text-sm text-emerald-700">
                  Quote reference <span className="font-semibold">{createdQuoteRef}</span> has been saved.
                </p>
              </div>
            </div>
          </div>
        ) : null}

        {quotesError ? (
          <div className="rounded-[28px] border border-rose-200 bg-rose-50 px-5 py-4">
            <p className="text-sm font-semibold text-rose-800">Failed to load quotes</p>
            <p className="mt-1 text-sm text-rose-700">{quotesError.message}</p>
          </div>
        ) : null}

        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          <StatCard label="Total Quotes" value={String(totalQuotes)} icon={FileText} />
          <StatCard label="Draft Quotes" value={String(draftQuotes)} icon={CircleDashed} />
          <StatCard label="Approved Quotes" value={String(approvedQuotes)} icon={BadgeCheck} />
          <StatCard label="Total Quote Value" value={formatCurrency(totalQuoteValue)} icon={IndianRupee} />
        </div>

        <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
          <InfoPanel
            title="Recent Quotes"
            action={
              <Link
                href="/agent/quotes/new"
                className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white transition hover:bg-slate-800"
              >
                <Plus className="h-4 w-4" />
                New Quote
              </Link>
            }
          >
            {quotes.length === 0 ? (
              <div className="rounded-[28px] border border-dashed border-slate-300 bg-slate-50 px-6 py-10 text-center">
                <p className="text-base font-semibold text-slate-900">No quotes found yet.</p>
                <p className="mt-2 text-sm text-slate-600">
                  Your quote list is empty. Create the first quote from the custom trip flow.
                </p>

                <div className="mt-5">
                  <Link
                    href="/trip-builder"
                    className="inline-flex items-center gap-2 rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-slate-400 hover:bg-slate-100"
                  >
                    <ReceiptText className="h-4 w-4" />
                    Go to Trip Builder
                  </Link>
                </div>
              </div>
            ) : (
              <div className="overflow-hidden rounded-[28px] border border-slate-200">
                <div className="overflow-x-auto">
                  <table className="min-w-full divide-y divide-slate-200">
                    <thead className="bg-slate-50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Quote
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Customer
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Travel
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Status
                        </th>
                        <th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Amount
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Created
                        </th>
                        <th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Action
                        </th>
                      </tr>
                    </thead>

                    <tbody className="divide-y divide-slate-200 bg-white">
                      {quotes.map((quote) => {
                        const payload = quote.builder_payload || {};
                        const departureCity = payload.departureCity || "—";
                        const travelDates = payload.travelDates || "—";
                        const nights = payload.nights || "—";
                        const adults = safeNumber(payload.adults);
                        const children = safeNumber(payload.children);
                        const travellerText = `${adults}A${children > 0 ? ` · ${children}C` : ""}`;

                        return (
                          <tr key={quote.id} className="align-top">
                            <td className="px-4 py-4">
                              <div>
                                <p className="text-sm font-semibold text-slate-950">
                                  {quote.destination || "Custom Trip Quote"}
                                </p>
                                <p className="mt-1 text-xs font-medium text-slate-500">{quote.quote_ref || "—"}</p>
                                <p className="mt-2 text-sm text-slate-600">
                                  {[quote.destination, departureCity].filter(Boolean).join(" · ") || "—"}
                                </p>
                              </div>
                            </td>

                            <td className="px-4 py-4">
                              <div>
                                <p className="text-sm font-medium text-slate-900">{quote.customer_name || "—"}</p>
                                <p className="mt-1 text-xs text-slate-500">{quote.customer_email || "—"}</p>
                                <p className="mt-1 text-xs text-slate-500">{quote.customer_phone || "—"}</p>
                              </div>
                            </td>

                            <td className="px-4 py-4">
                              <div>
                                <p className="text-sm font-medium text-slate-900">{travelDates}</p>
                                <p className="mt-1 text-xs text-slate-500">
                                  {[nights, travellerText].filter(Boolean).join(" · ")}
                                </p>
                              </div>
                            </td>

                            <td className="px-4 py-4">
                              <span
                                className={[
                                  "inline-flex rounded-full border px-3 py-1 text-xs font-semibold",
                                  getStatusClasses(quote.status),
                                ].join(" ")}
                              >
                                {normalizeStatus(quote.status)}
                              </span>
                            </td>

                            <td className="px-4 py-4 text-right">
                              <p className="text-sm font-semibold text-slate-950">
                                {formatCurrency(quote.amount)}
                              </p>
                            </td>

                            <td className="px-4 py-4">
                              <div>
                                <p className="text-sm text-slate-900">{formatDate(quote.created_at)}</p>
                                <p className="mt-1 text-xs text-slate-500">{formatDateTime(quote.created_at)}</p>
                              </div>
                            </td>

                            <td className="px-4 py-4 text-right">
                              <Link
                                href={`/agent/quotes/${quote.id}`}
                                className="inline-flex rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50"
                              >
                                View
                              </Link>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </InfoPanel>

          <div className="space-y-6">
            <InfoPanel title="Quote Pipeline">
              <div className="space-y-4">
                <div className="rounded-[24px] border border-slate-200 bg-slate-50 p-4">
                  <div className="flex items-start gap-3">
                    <Clock3 className="mt-0.5 h-4 w-4 text-slate-500" />
                    <div>
                      <p className="text-sm font-semibold text-slate-900">Draft</p>
                      <p className="mt-1 text-2xl font-semibold text-slate-950">{draftQuotes}</p>
                      <p className="mt-1 text-sm text-slate-600">Quotes created but not yet progressed.</p>
                    </div>
                  </div>
                </div>

                <div className="rounded-[24px] border border-slate-200 bg-slate-50 p-4">
                  <div className="flex items-start gap-3">
                    <BadgeCheck className="mt-0.5 h-4 w-4 text-slate-500" />
                    <div>
                      <p className="text-sm font-semibold text-slate-900">Approved</p>
                      <p className="mt-1 text-2xl font-semibold text-slate-950">{approvedQuotes}</p>
                      <p className="mt-1 text-sm text-slate-600">Quotes already approved in the pipeline.</p>
                    </div>
                  </div>
                </div>

                <div className="rounded-[24px] border border-slate-200 bg-slate-50 p-4">
                  <div className="flex items-start gap-3">
                    <IndianRupee className="mt-0.5 h-4 w-4 text-slate-500" />
                    <div>
                      <p className="text-sm font-semibold text-slate-900">Total Value</p>
                      <p className="mt-1 text-2xl font-semibold text-slate-950">
                        {formatCurrency(totalQuoteValue)}
                      </p>
                      <p className="mt-1 text-sm text-slate-600">Total value across all quotes for this agent.</p>
                    </div>
                  </div>
                </div>
              </div>
            </InfoPanel>

            <InfoPanel title="Quick Actions">
              <div className="space-y-3">
                <Link
                  href="/trip-builder"
                  className="flex items-center justify-between rounded-[22px] border border-slate-200 bg-white px-4 py-4 transition hover:border-slate-300 hover:bg-slate-50"
                >
                  <div>
                    <p className="text-sm font-semibold text-slate-950">Create New Quote</p>
                    <p className="mt-1 text-sm text-slate-600">
                      Start a fresh custom trip and convert it into a quote.
                    </p>
                  </div>
                  <Plus className="h-4 w-4 text-slate-500" />
                </Link>

                <Link
                  href="/agent/dashboard"
                  className="flex items-center justify-between rounded-[22px] border border-slate-200 bg-white px-4 py-4 transition hover:border-slate-300 hover:bg-slate-50"
                >
                  <div>
                    <p className="text-sm font-semibold text-slate-950">Back to Dashboard</p>
                    <p className="mt-1 text-sm text-slate-600">Return to your main agent control panel.</p>
                  </div>
                  <FileText className="h-4 w-4 text-slate-500" />
                </Link>
              </div>
            </InfoPanel>
          </div>
        </div>
      </div>
    </PortalShell>
  );
}